# Site settings
author: Edward-Beck
title: 
header-img: img/home-bg.png
email: edward.beck906@yahoo.com
copyright_name: Edward-Beck
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Edward-Beck

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
